from __future__ import annotations

from collections import Counter
from copy import deepcopy

from app.services.feed.store import create_source_feed_record, create_source_record


DEFAULT_NEWS_SOURCES: list[dict] = [
    {
        "name": "BBC News",
        "website_url": "https://www.bbc.com/news",
        "rss_url": "https://feeds.bbci.co.uk/news/world/rss.xml",
        "country": "United Kingdom",
        "language": "English",
        "region": "Europe",
        "source_size": "major",
        "source_type": "broadcaster",
        "political_context": "UK public-service broadcaster with international news coverage.",
        "notes": "Official BBC feed documentation lists BBC News RSS feeds and terms.",
    },
    {
        "name": "The Guardian",
        "website_url": "https://www.theguardian.com/world",
        "rss_url": "https://www.theguardian.com/world/rss",
        "country": "United Kingdom",
        "language": "English",
        "region": "Europe",
        "source_size": "major",
        "source_type": "newspaper",
        "political_context": "Independent UK newspaper owned by the Scott Trust; editorial stance often liberal/progressive.",
        "notes": "Guardian help documents that index pages can expose RSS by adding /rss.",
    },
    {
        "name": "Reuters",
        "website_url": "https://www.reuters.com",
        "rss_url": None,
        "country": "United Kingdom",
        "language": "English",
        "region": "Global",
        "source_size": "major",
        "source_type": "news_agency",
        "political_context": "Global wire service with broad institutional and market coverage.",
        "notes": "Website-only seed because a stable public RSS endpoint was not confirmed.",
    },
    {
        "name": "Associated Press",
        "website_url": "https://apnews.com",
        "rss_url": None,
        "country": "United States",
        "language": "English",
        "region": "North America",
        "source_size": "major",
        "source_type": "news_agency",
        "political_context": "US-based nonprofit wire service with global distribution.",
        "notes": "Website-only seed because a stable public RSS endpoint was not confirmed.",
    },
    {
        "name": "Agence France-Presse",
        "website_url": "https://www.afp.com/en",
        "rss_url": None,
        "country": "France",
        "language": "English",
        "region": "Europe",
        "source_size": "major",
        "source_type": "news_agency",
        "political_context": "France-headquartered global news agency.",
        "notes": "Website-only source profile seed.",
    },
    {
        "name": "France 24 English",
        "website_url": "https://www.france24.com/en",
        "rss_url": "https://www.france24.com/en/rss",
        "country": "France",
        "language": "English",
        "region": "Europe",
        "source_size": "major",
        "source_type": "broadcaster",
        "political_context": "French state-funded international broadcaster.",
        "notes": "Public RSS endpoint verified during implementation.",
    },
    {
        "name": "RFI English",
        "website_url": "https://www.rfi.fr/en",
        "rss_url": "https://www.rfi.fr/en/rss",
        "country": "France",
        "language": "English",
        "region": "Europe",
        "source_size": "medium",
        "source_type": "broadcaster",
        "political_context": "French public international radio network.",
        "notes": "Public RSS endpoint verified during implementation.",
    },
    {
        "name": "RFI Francais",
        "website_url": "https://www.rfi.fr/fr",
        "rss_url": "https://www.rfi.fr/fr/rss",
        "country": "France",
        "language": "French",
        "region": "Europe",
        "source_size": "medium",
        "source_type": "broadcaster",
        "political_context": "French public international radio network.",
        "notes": "French-language public RSS endpoint verified during implementation.",
    },
    {
        "name": "Deutsche Welle",
        "website_url": "https://www.dw.com/en/top-stories/s-9097",
        "rss_url": "https://rss.dw.com/rdf/rss-en-all",
        "country": "Germany",
        "language": "English",
        "region": "Europe",
        "source_size": "major",
        "source_type": "broadcaster",
        "political_context": "German public international broadcaster.",
        "notes": "Public RSS endpoint verified during implementation.",
    },
    {
        "name": "Le Monde",
        "website_url": "https://www.lemonde.fr",
        "rss_url": "https://www.lemonde.fr/international/rss_full.xml",
        "country": "France",
        "language": "French",
        "region": "Europe",
        "source_size": "major",
        "source_type": "newspaper",
        "political_context": "French national newspaper with international coverage.",
        "notes": "Le Monde documents RSS feeds and states usage limits; verify terms before scaled use.",
    },
    {
        "name": "Le Monde in English",
        "website_url": "https://www.lemonde.fr/en",
        "rss_url": "https://www.lemonde.fr/en/international/rss_full.xml",
        "country": "France",
        "language": "English",
        "region": "Europe",
        "source_size": "medium",
        "source_type": "newspaper",
        "political_context": "English edition of Le Monde, translated/adapted from the French newsroom.",
        "notes": "Le Monde documents RSS feeds and usage limits; verify terms before scaled use.",
    },
    {
        "name": "El Pais",
        "website_url": "https://elpais.com",
        "rss_url": "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
        "country": "Spain",
        "language": "Spanish",
        "region": "Europe",
        "source_size": "major",
        "source_type": "newspaper",
        "political_context": "Spanish national newspaper with broad international coverage.",
        "notes": "Public RSS endpoint verified during implementation.",
    },
    {
        "name": "Al Jazeera English",
        "website_url": "https://www.aljazeera.com",
        "rss_url": "https://www.aljazeera.com/xml/rss/all.xml",
        "country": "Qatar",
        "language": "English",
        "region": "Middle East",
        "source_size": "major",
        "source_type": "broadcaster",
        "political_context": "Qatar-funded international broadcaster; useful for Middle East and Global South framing comparison.",
        "notes": "Public RSS endpoint verified during implementation.",
    },
    {
        "name": "Anadolu Agency",
        "website_url": "https://www.aa.com.tr",
        "rss_url": "https://www.aa.com.tr/tr/rss/default?cat=guncel",
        "country": "Turkey",
        "language": "Turkish",
        "region": "Middle East",
        "source_size": "major",
        "source_type": "state_media",
        "political_context": "Turkish state-run news agency.",
        "notes": "Public Turkish RSS endpoint verified during implementation.",
    },
    {
        "name": "IRNA",
        "website_url": "https://www.irna.ir",
        "rss_url": "https://www.irna.ir/rss",
        "country": "Iran",
        "language": "Persian",
        "region": "Middle East",
        "source_size": "major",
        "source_type": "state_media",
        "political_context": "Islamic Republic News Agency; official Iranian state news agency.",
        "notes": "Public RSS endpoint verified during implementation.",
    },
    {
        "name": "Middle East Eye",
        "website_url": "https://www.middleeasteye.net",
        "rss_url": "https://www.middleeasteye.net/rss",
        "country": "United Kingdom",
        "language": "English",
        "region": "Middle East",
        "source_size": "medium",
        "source_type": "independent",
        "political_context": "UK-based outlet focused on the Middle East and North Africa.",
        "notes": "Public RSS endpoint verified during implementation.",
    },
    {
        "name": "Times of Israel",
        "website_url": "https://www.timesofisrael.com",
        "rss_url": "https://www.timesofisrael.com/feed/",
        "country": "Israel",
        "language": "English",
        "region": "Middle East",
        "source_size": "medium",
        "source_type": "newspaper",
        "political_context": "Israel-based English-language outlet.",
        "notes": "Public RSS endpoint verified during implementation.",
    },
    {
        "name": "Dawn",
        "website_url": "https://www.dawn.com",
        "rss_url": "https://www.dawn.com/feeds/latest-news",
        "country": "Pakistan",
        "language": "English",
        "region": "South Asia",
        "source_size": "major",
        "source_type": "newspaper",
        "political_context": "Pakistani national newspaper with regional coverage.",
        "notes": "Public RSS endpoint verified during implementation.",
    },
    {
        "name": "The Hindu International",
        "website_url": "https://www.thehindu.com/news/international/",
        "rss_url": "https://www.thehindu.com/news/international/feeder/default.rss",
        "country": "India",
        "language": "English",
        "region": "South Asia",
        "source_size": "major",
        "source_type": "newspaper",
        "political_context": "Indian national newspaper; useful for South Asia and international framing comparison.",
        "notes": "Public international RSS endpoint verified during implementation.",
    },
    {
        "name": "Hindustan Times World",
        "website_url": "https://www.hindustantimes.com/world-news",
        "rss_url": "https://www.hindustantimes.com/feeds/rss/world-news/rssfeed.xml",
        "country": "India",
        "language": "English",
        "region": "South Asia",
        "source_size": "major",
        "source_type": "newspaper",
        "political_context": "Indian national newspaper with international section feed.",
        "notes": "Public world-news RSS endpoint verified during implementation.",
    },
    {
        "name": "NHK News",
        "website_url": "https://www3.nhk.or.jp/news/",
        "rss_url": "https://www3.nhk.or.jp/rss/news/cat0.xml",
        "country": "Japan",
        "language": "Japanese",
        "region": "East Asia",
        "source_size": "major",
        "source_type": "broadcaster",
        "political_context": "Japanese public broadcaster.",
        "notes": "Public Japanese RSS endpoint verified during implementation.",
    },
    {
        "name": "Japan Times",
        "website_url": "https://www.japantimes.co.jp",
        "rss_url": "https://www.japantimes.co.jp/feed/",
        "country": "Japan",
        "language": "English",
        "region": "East Asia",
        "source_size": "medium",
        "source_type": "newspaper",
        "political_context": "Japan-based English-language newspaper.",
        "notes": "Public RSS endpoint verified during implementation.",
    },
    {
        "name": "Yonhap News Agency",
        "website_url": "https://en.yna.co.kr",
        "rss_url": "https://en.yna.co.kr/RSS/news.xml",
        "country": "South Korea",
        "language": "English",
        "region": "East Asia",
        "source_size": "major",
        "source_type": "news_agency",
        "political_context": "South Korean news agency.",
        "notes": "Public English RSS endpoint verified during implementation.",
    },
    {
        "name": "South China Morning Post",
        "website_url": "https://www.scmp.com",
        "rss_url": "https://www.scmp.com/rss/91/feed",
        "country": "Hong Kong",
        "language": "English",
        "region": "East Asia",
        "source_size": "major",
        "source_type": "newspaper",
        "political_context": "Hong Kong-based newspaper with regional and China coverage.",
        "notes": "Public RSS endpoint verified during implementation.",
    },
    {
        "name": "ABC News Australia",
        "website_url": "https://www.abc.net.au/news",
        "rss_url": "https://www.abc.net.au/news/feed/51120/rss.xml",
        "country": "Australia",
        "language": "English",
        "region": "Oceania",
        "source_size": "major",
        "source_type": "broadcaster",
        "political_context": "Australian public broadcaster.",
        "notes": "Public RSS endpoint verified during implementation.",
    },
    {
        "name": "CBC World",
        "website_url": "https://www.cbc.ca/news/world",
        "rss_url": "https://www.cbc.ca/cmlink/rss-world",
        "country": "Canada",
        "language": "English",
        "region": "North America",
        "source_size": "major",
        "source_type": "broadcaster",
        "political_context": "Canadian public broadcaster.",
        "notes": "Public world RSS endpoint verified during implementation.",
    },
    {
        "name": "NPR",
        "website_url": "https://www.npr.org",
        "rss_url": None,
        "country": "United States",
        "language": "English",
        "region": "North America",
        "source_size": "major",
        "source_type": "broadcaster",
        "political_context": "US public radio network; public RSS availability varies by program/API path.",
        "notes": "Website-only seed because a stable general public RSS endpoint was not confirmed.",
    },
    {
        "name": "New York Times World",
        "website_url": "https://www.nytimes.com/section/world",
        "rss_url": "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
        "country": "United States",
        "language": "English",
        "region": "North America",
        "source_size": "major",
        "source_type": "newspaper",
        "political_context": "US newspaper with global coverage.",
        "notes": "Public world RSS endpoint verified during implementation; commercial terms should be reviewed before production-scale use.",
    },
    {
        "name": "Christian Science Monitor World",
        "website_url": "https://www.csmonitor.com/World",
        "rss_url": "https://rss.csmonitor.com/feeds/world",
        "country": "United States",
        "language": "English",
        "region": "North America",
        "source_size": "medium",
        "source_type": "newspaper",
        "political_context": "US-based international reporting outlet.",
        "notes": "Public RSS endpoint verified during implementation.",
    },
    {
        "name": "Axios",
        "website_url": "https://www.axios.com",
        "rss_url": "https://www.axios.com/feeds/feed.rss",
        "country": "United States",
        "language": "English",
        "region": "North America",
        "source_size": "medium",
        "source_type": "independent",
        "political_context": "US digital newsroom with concise policy and politics coverage.",
        "notes": "Public RSS endpoint verified during implementation.",
    },
    {
        "name": "Agencia Brasil",
        "website_url": "https://agenciabrasil.ebc.com.br",
        "rss_url": "https://agenciabrasil.ebc.com.br/rss/ultimasnoticias/feed.xml",
        "country": "Brazil",
        "language": "Portuguese",
        "region": "Latin America",
        "source_size": "major",
        "source_type": "state_media",
        "political_context": "Brazilian public news agency operated by EBC.",
        "notes": "Public RSS endpoint verified during implementation.",
    },
    {
        "name": "Folha de S.Paulo",
        "website_url": "https://www.folha.uol.com.br",
        "rss_url": None,
        "country": "Brazil",
        "language": "Portuguese",
        "region": "Latin America",
        "source_size": "major",
        "source_type": "newspaper",
        "political_context": "Brazilian national newspaper.",
        "notes": "Website-only source profile seed.",
    },
    {
        "name": "La Jornada",
        "website_url": "https://www.jornada.com.mx",
        "rss_url": None,
        "country": "Mexico",
        "language": "Spanish",
        "region": "Latin America",
        "source_size": "medium",
        "source_type": "newspaper",
        "political_context": "Mexican newspaper often associated with left-leaning editorial perspectives.",
        "notes": "Website-only source profile seed.",
    },
    {
        "name": "Clarin",
        "website_url": "https://www.clarin.com",
        "rss_url": None,
        "country": "Argentina",
        "language": "Spanish",
        "region": "Latin America",
        "source_size": "major",
        "source_type": "newspaper",
        "political_context": "Argentine national newspaper and media group.",
        "notes": "Website-only source profile seed.",
    },
    {
        "name": "Daily Maverick",
        "website_url": "https://www.dailymaverick.co.za",
        "rss_url": "https://www.dailymaverick.co.za/dmrss/",
        "country": "South Africa",
        "language": "English",
        "region": "Africa",
        "source_size": "medium",
        "source_type": "independent",
        "political_context": "South African independent newsroom with investigative and political coverage.",
        "notes": "Public RSS endpoint verified during implementation.",
    },
    {
        "name": "Egypt Independent",
        "website_url": "https://www.egyptindependent.com",
        "rss_url": "https://www.egyptindependent.com/feed/",
        "country": "Egypt",
        "language": "English",
        "region": "Africa",
        "source_size": "small",
        "source_type": "independent",
        "political_context": "Egypt-focused English-language outlet.",
        "notes": "Public RSS endpoint verified during implementation.",
    },
    {
        "name": "Premium Times",
        "website_url": "https://www.premiumtimesng.com",
        "rss_url": None,
        "country": "Nigeria",
        "language": "English",
        "region": "Africa",
        "source_size": "medium",
        "source_type": "independent",
        "political_context": "Nigerian investigative and public-interest newsroom.",
        "notes": "Website-only source profile seed.",
    },
    {
        "name": "The Conversation Africa",
        "website_url": "https://theconversation.com/africa",
        "rss_url": None,
        "country": "South Africa",
        "language": "English",
        "region": "Africa",
        "source_size": "medium",
        "source_type": "independent",
        "political_context": "Academic expert commentary network; useful for background context more than breaking news.",
        "notes": "Website-only source profile seed.",
    },
    {
        "name": "Bellingcat",
        "website_url": "https://www.bellingcat.com",
        "rss_url": "https://www.bellingcat.com/feed/",
        "country": "Netherlands",
        "language": "English",
        "region": "Global",
        "source_size": "niche",
        "source_type": "independent",
        "political_context": "Open-source investigative collective; useful as OSINT context, not a wire feed.",
        "notes": "Public RSS endpoint verified during implementation.",
    },
    {
        "name": "ICIJ",
        "website_url": "https://www.icij.org",
        "rss_url": "https://www.icij.org/feed/",
        "country": "United States",
        "language": "English",
        "region": "Global",
        "source_size": "niche",
        "source_type": "independent",
        "political_context": "International investigative journalism consortium.",
        "notes": "Public RSS endpoint verified during implementation.",
    },
    {
        "name": "Human Rights Watch",
        "website_url": "https://www.hrw.org",
        "rss_url": "https://www.hrw.org/rss/news",
        "country": "United States",
        "language": "English",
        "region": "Global",
        "source_size": "medium",
        "source_type": "NGO",
        "political_context": "International human-rights NGO; should be treated as advocacy/research context.",
        "notes": "Public RSS endpoint verified during implementation.",
    },
    {
        "name": "UN News",
        "website_url": "https://news.un.org/en",
        "rss_url": "https://news.un.org/feed/subscribe/en/news/all/rss.xml",
        "country": "United Nations",
        "language": "English",
        "region": "Global",
        "source_size": "major",
        "source_type": "official",
        "political_context": "Official United Nations news service.",
        "notes": "Public English RSS endpoint verified during implementation.",
    },
    {
        "name": "UN News Arabic",
        "website_url": "https://news.un.org/ar",
        "rss_url": "https://news.un.org/feed/subscribe/ar/news/all/rss.xml",
        "country": "United Nations",
        "language": "Arabic",
        "region": "Global",
        "source_size": "major",
        "source_type": "official",
        "political_context": "Official United Nations Arabic news service.",
        "notes": "Public Arabic RSS endpoint verified during implementation.",
    },
    {
        "name": "Voice of America",
        "website_url": "https://www.voanews.com",
        "rss_url": None,
        "country": "United States",
        "language": "English",
        "region": "Global",
        "source_size": "major",
        "source_type": "state_media",
        "political_context": "US government-funded international broadcaster.",
        "notes": "Website-only source profile seed.",
    },
    {
        "name": "Xinhua",
        "website_url": "https://english.news.cn",
        "rss_url": None,
        "country": "China",
        "language": "English",
        "region": "East Asia",
        "source_size": "major",
        "source_type": "state_media",
        "political_context": "Official state news agency of China.",
        "notes": "Website-only source profile seed.",
    },
    {
        "name": "TASS",
        "website_url": "https://tass.com",
        "rss_url": None,
        "country": "Russia",
        "language": "English",
        "region": "Europe",
        "source_size": "major",
        "source_type": "state_media",
        "political_context": "Russian state news agency.",
        "notes": "Website-only source profile seed.",
    },
    {
        "name": "Kyiv Independent",
        "website_url": "https://kyivindependent.com",
        "rss_url": None,
        "country": "Ukraine",
        "language": "English",
        "region": "Europe",
        "source_size": "small",
        "source_type": "independent",
        "political_context": "Ukrainian independent English-language outlet.",
        "notes": "Website-only source profile seed.",
    },
]


def _source_summary(sources: list[dict]) -> dict:
    countries = Counter(item.get("country") for item in sources if item.get("country"))
    languages = Counter(item.get("language") for item in sources if item.get("language"))
    regions = Counter(item.get("region") for item in sources if item.get("region"))
    source_types = Counter(item.get("source_type") for item in sources if item.get("source_type"))
    source_sizes = Counter(item.get("source_size") for item in sources if item.get("source_size"))
    return {
        "source_count": len(sources),
        "rss_count": sum(1 for item in sources if item.get("rss_url")),
        "country_count": len(countries),
        "language_count": len(languages),
        "region_count": len(regions),
        "countries": dict(sorted(countries.items())),
        "languages": dict(sorted(languages.items())),
        "regions": dict(sorted(regions.items())),
        "source_types": dict(sorted(source_types.items())),
        "source_sizes": dict(sorted(source_sizes.items())),
    }


def preview_default_sources(limit: int | None = None) -> dict:
    max_items = len(DEFAULT_NEWS_SOURCES) if limit is None else max(1, min(int(limit), len(DEFAULT_NEWS_SOURCES)))
    sources = deepcopy(DEFAULT_NEWS_SOURCES[:max_items])
    return {
        "summary": _source_summary(sources),
        "sources": sources,
        "limitations": [
            "Default sources are starting metadata, not credibility verdicts.",
            "RSS endpoints can change; verify feeds and terms before production-scale ingestion.",
            "Political context fields are descriptive and should be refined by operators.",
        ],
    }


def seed_default_sources(limit: int | None = None) -> dict:
    preview = preview_default_sources(limit=limit)
    seeded_sources = []
    seeded_feeds = []

    for item in preview["sources"]:
        source = create_source_record(
            name=item["name"],
            website_url=item.get("website_url"),
            rss_url=item.get("rss_url"),
            country=item.get("country"),
            language=item.get("language"),
            region=item.get("region"),
            political_context=item.get("political_context"),
            source_size=item.get("source_size"),
            source_type=item.get("source_type"),
            credibility_notes=(
                "Default metadata seed. Treat source profile as context, not a truth or credibility verdict."
            ),
            notes=item.get("notes"),
            is_default=True,
        )
        feed = None
        if item.get("rss_url"):
            feed = create_source_feed_record(
                source_id=source["id"],
                feed_url=item["rss_url"],
                feed_type="rss",
                title=f"{item['name']} RSS",
                language=item.get("language"),
                country=item.get("country"),
                status="active",
                fetch_interval_minutes=120,
            )
            seeded_feeds.append(feed)
        seeded_sources.append({**source, "seed_rss_url": item.get("rss_url"), "seed_feed": feed})

    return {
        "summary": {
            **preview["summary"],
            "seeded_source_count": len(seeded_sources),
            "seeded_feed_count": len(seeded_feeds),
        },
        "sources": seeded_sources,
        "feeds": seeded_feeds,
        "limitations": preview["limitations"],
    }
